[mysql]
# Streamlit Cloud에서 접속할 서버의 IP 주소입니다.
# 로컬이 아닌 외부에서 접속해야 하므로 반드시 '공인 IP'를 입력해야 합니다.
host = "211.179.110.120" 

# 데이터베이스 접속 사용자 이름
user = "madang_user"

# 데이터베이스 접속 비밀번호
passwd = "madang_user_1234"

# 접속할 데이터베이스 이름
db = "madang"

# 데이터 인코딩 방식
charset = "utf8mb4"
